function Interfata(V1,Ampl2,Ampl3,f2,f3,Tipf2,Tipf3,R1,R2,R3,Rn,TipR1,TipR2,TipR3,TipRn,TipSemnal,Va1,Va2,N,n,Ph2,Ph3,A2,A3,k)


switch Tipf2
    case 1
        F2=f2;
    case 2
        F2=f2*10^3;
end

switch Tipf3
    case 1
        F3=f3;
    case 2
        F3=f3*10^3;
end

T2=1/F2;
T3=1/F3;

t2=0:T2./n:N.*T2;
t3=0:T3./n:N.*T3;;

f4=gcd(f2,f3);
T4=1./f4;
t4=0:T4./n:N.*T4;


V2=A2+Ampl2*sin(2*pi*F2*t2+Ph2);

switch TipR1
    case 1
        r1=R1;
    case 2
        r1=R1*10^3;
end;

switch TipR2
    case 1
        r2=R2;
    case 2
        r2=R2*10^3;
end;

switch TipR3
    case 1
        r3=R3;
    case 2
        r3=R3*10^3;
end;

switch TipRn
    case 1
        rn=Rn;
    case 2
        rn=Rn*10^3;
end;

switch TipSemnal
    case 1
        V3=A3+Ampl3*sin(2*pi*F3*t3+Ph3);
    case 2
        V3=A3+Ampl3*square(2*pi*F3*t3+Ph3,50);
    case 3
        V3=A3+Ampl3*sawtooth(2*pi*F3*t3+Ph3,0.5);
    case 4
        V3=A3+Ampl3*sawtooth(2*pi*F3*t3+Ph3);
end

I1=V1/r1;
I2=V2/r2;
I3=V3/r3;

In=I1+I2+I3;



nt=length(t4);
for i=1:nt
    Out(i)=-In(i)*rn;
    if Out(i)>Va1
        Out(i)=Va1;
    elseif Out(i)<Va2
        Out(i)=Va2;
    
    end
end

Fig=figure('Name','Circuit de insumare cu AO',...
    'Units','normalized',...
    'Position',[.2 .2 .7 .7],...
    'NumberTitle','off','Color','#8e82fe');
        


Group1=uipanel('Title','Date de intrare:',...
    'BackgroundColor','#95d0fc',...
    'FontSize',10,...
    'Position',[0.01 0.35 0.2 0.6],'Parent',Fig)

Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.03 0.8 0.23 0.08],...
    'BackgroundColor','#95d0fc',...
    'foregroundcolor','black',...
    'String','Va1=',...
    'Parent',Group1);

Be=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.26 0.8 0.23 0.08],...
    'foregroundcolor','black',...
    'String',num2str(Va1),...
    'Callback','Va1=str2num(get(gco,''String''))',...
    'Parent',Group1);



Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.03 0.7 0.23 0.08],...
    'BackgroundColor','#95d0fc',...
    'foregroundcolor','black',...
    'String','Va2=',...
    'Parent',Group1);

Be=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.26 0.7 0.23 0.08],...
    'foregroundcolor','black',...
    'String',num2str(Va2),...
    'Callback','Va2=str2num(get(gco,''String''))',...
    'Parent',Group1);



Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.03 0.6 0.23 0.08],...
    'BackgroundColor','#95d0fc',...
    'foregroundcolor','black',...
    'String','n=',...
    'Parent',Group1);

Be=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.26 0.6 0.23 0.08],...
    'foregroundcolor','black',...
    'String',num2str(n),...
    'Callback','n=str2num(get(gco,''String''))',...
    'Parent',Group1);



Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.03 0.5 0.23 0.08],...
    'BackgroundColor','#95d0fc',...
    'foregroundcolor','black',...
    'String','N=',...
    'Parent',Group1);

Be=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.26 0.5 0.23 0.08],...
    'foregroundcolor','black',...
    'String',num2str(N),...
    'Callback','N=str2num(get(gco,''String''))',...
    'Parent',Group1);




Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.03 0.4 0.23 0.08],...
    'BackgroundColor','#95d0fc',...
    'foregroundcolor','black',...
    'String','R1=',...
    'Parent',Group1);



Be=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.26 0.4 0.23 0.08],...
    'foregroundcolor','black',...
    'String',num2str(R1),...
    'Callback','R1=str2num(get(gco,''String''))',...
    'Parent',Group1);



Pm=uicontrol("Style","popupmenu",...
    'Units','normalized',...
    'Position',[0.49 0.4 0.23 0.08],...
    'String','Ohm|kOhm',...
    'Value',TipR1,...
    'Callback','TipR1=get(gco,''Value'')',...
    'Parent',Group1);

Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.03 0.3 0.23 0.08],...
    'BackgroundColor','#95d0fc',...
    'foregroundcolor','black',...
    'String','R2=',...
    'Parent',Group1);



Be=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.26 0.3 0.23 0.08],...
    'foregroundcolor','black',...
    'String',num2str(R2),...
    'Callback','R2=str2num(get(gco,''String''))',...
    'Parent',Group1);



Pm=uicontrol("Style","popupmenu",...
    'Units','normalized',...
    'Position',[0.49 0.3 0.23 0.08],...
    'String','Ohm|kOhm',...
    'Value',TipR2,...
    'Callback','TipR2=get(gco,''Value'')',...
    'Parent',Group1);

Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.03 0.2 0.23 0.08],...
    'BackgroundColor','#95d0fc',...
    'foregroundcolor','black',...
    'String','R3=',...
    'Parent',Group1);



Be=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.26 0.2 0.23 0.08],...
    'foregroundcolor','black',...
    'String',num2str(R3),...
    'Callback','R3=str2num(get(gco,''String''))',...
    'Parent',Group1);



Pm=uicontrol("Style","popupmenu",...
    'Units','normalized',...
    'Position',[0.49 0.2 0.23 0.08],...
    'String','Ohm|kOhm',...
    'Value',TipR3,...
    'Callback','TipR3=get(gco,''Value'')',...
    'Parent',Group1);

Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.03 0.1 0.23 0.08],...
    'BackgroundColor','#95d0fc',...
    'foregroundcolor','black',...
    'String','Rn=',...
    'Parent',Group1);



Be=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.26 0.1 0.23 0.08],...
    'foregroundcolor','black',...
    'String',num2str(Rn),...
    'Callback','Rn=str2num(get(gco,''String''))',...
    'Parent',Group1);



Pm=uicontrol("Style","popupmenu",...
    'Units','normalized',...
    'Position',[0.49 0.1 0.23 0.08],...
    'String','Ohm|kOhm',...
    'Value',TipRn,...
    'Callback','TipRn=get(gco,''Value'')',...
    'Parent',Group1);



Group2=uipanel('Title','Circuit:',...
    'BackgroundColor','#95d0fc',...
    'FontSize',10,...
    'Position',[0.01 0.05 0.2 0.3]);

img=imread('poza.png');
image(img);
grid off;
set(gca,'units','normalized','position',[0.01 0.25 1 .8], 'parent', Group2);

Group3=uipanel('Title','Calcule:',...
    'BackgroundColor','#95d0fc',...
    'FontSize',10,...
    'Position',[0.21 0.62 0.2 0.33]);

Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.03 0.9 0.23 0.08],...
    'BackgroundColor','#95d0fc',...
    'foregroundcolor','black',...
    'String','I1=',...
    'Parent',Group3);

Be=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.6 0.9 0.23 0.08],...
    'foregroundcolor','black',...
    'String',num2str(I1),...
    'Parent',Group3);

Bt2=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.03 0.74 0.23 0.08],...
    'BackgroundColor','#95d0fc',...
    'foregroundcolor','black',...
    'String','I2(k)=',...
    'Parent',Group3);

Be=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.6 0.74 0.23 0.08],...
    'foregroundcolor','black',...
    'String',num2str(I2(k)),...
    'Parent',Group3);

Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.03 0.58 0.23 0.08],...
    'BackgroundColor','#95d0fc',...
    'foregroundcolor','black',...
    'String','I3(k)=',...
    'Parent',Group3);

Be=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.6 0.58 0.23 0.08],...
    'foregroundcolor','black',...
    'String',num2str(I3(k)),...
    'Parent',Group3);

Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.03 0.42 0.23 0.08],...
    'BackgroundColor','#95d0fc',...
    'foregroundcolor','black',...
    'String','In(k)=',...
    'Parent',Group3);

Be=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.6 0.42 0.23 0.08],...
    'foregroundcolor','black',...
    'String',num2str(In(k)),...
    'Parent',Group3);

Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.03 0.26 0.23 0.08],...
    'BackgroundColor','#95d0fc',...
    'foregroundcolor','black',...
    'String','Vout(k)=',...
    'Parent',Group3);

Be=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.6 0.26 0.23 0.08],...
    'foregroundcolor','black',...
    'String',num2str(Out(k)),...
    'Parent',Group3);

Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.03 0.10 0.23 0.08],...
    'BackgroundColor','#95d0fc',...
    'foregroundcolor','black',...
    'String','k=',...
    'Parent',Group3);

Be=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.6 0.10 0.23 0.08],...
    'foregroundcolor','black',...
    'String',num2str(k),...
    'Callback','k=str2num(get(gco,''String''))',...
    'Parent',Group3);





Group5=uipanel('Title','Circuit sumator:',...
    'BackgroundColor','#95d0fc',...
    'FontSize',10,...
    'Position',[0.43 0.07 0.55 0.9]);



if(r1 == 0 || r2==0 || r3==0 || rn==0 || f2==0 || f3==0 || (Ampl2<=0 && A2>0) || (Ampl3<=0 && A3>0) )

    Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.5 0.5 0.23 0.08],...
    'BackgroundColor','#95d0fc',...
    'foregroundcolor','black',...
    'String','Eroare!!! Parametrul nu poate avea valoarea 0!!!',...
    'Parent',Group5);

else

 
axes(Group5);
subplot(221);
plot(t2,V2,'-or');
title('Semnalul V2:');
xlabel('Timp[s]');
ylabel('Amplitudine [V]');
legend('V2');
hold on;
grid on;



subplot(222);
plot(t3,V3,':+b');
title('Semnalul V3:');
xlabel('Timp[s]');
ylabel('Amplitudine [V]');
legend('V3');
hold on;
grid on;


subplot(212);
plot(t4,Out,'-sm');
title('Reprezentare Vout:');
xlabel('Timp[s]');
ylabel('Amplitudine [V]');
grid on;

end


uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.27 0.05 0.08 .05],...
'string','Calcul',...
'Callback','close;Interfata(V1,Ampl2,Ampl3,f2,f3,Tipf2,Tipf3,R1,R2,R3,Rn,TipR1,TipR2,TipR3,TipRn,TipSemnal,Va1,Va2,N,n,Ph2,Ph3,A2,A3,k)');

Group6=uipanel('Title','Editare parametri semnale',...
    'BackgroundColor','#95d0fc',...
    'FontSize',10,...
    'Position',[0.21 0.12 0.2 0.5],'Parent',Fig);

Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.03 0.95 0.10 0.05],...
    'BackgroundColor','#95d0fc',...
    'foregroundcolor','black',...
    'String','V1=',...
    'Parent',Group6);


Be=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.33 0.95 0.23 0.05],...
    'foregroundcolor','black',...
    'String',num2str(V1),...
    'Callback','V1=str2num(get(gco,''String''))',...
    'Parent',Group6);



Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.03 0.85 0.10 0.05],...
    'BackgroundColor','#95d0fc',...
    'foregroundcolor','black',...
    'String','V2:',...
    'Parent',Group6);

Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.13 0.85 0.2 0.05],...
    'BackgroundColor','#95d0fc',...
    'foregroundcolor','black',...
    'String','Ampl2=',...
    'Parent',Group6);

Be=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.33 0.85 0.23 0.05],...
    'foregroundcolor','black',...
    'String',num2str(Ampl2),...
    'Callback','Ampl2=str2num(get(gco,''String''))',...
    'Parent',Group6);

Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.13 0.75 0.2 0.05],...
    'BackgroundColor','#95d0fc',...
    'foregroundcolor','black',...
    'String','A2=',...
    'Parent',Group6);

Be=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.33 0.75 0.23 0.05],...
    'foregroundcolor','black',...
    'String',num2str(A2),...
    'Callback','A2=str2num(get(gco,''String''))',...
    'Parent',Group6);

Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.13 0.65 0.23 0.05],...
    'BackgroundColor','#95d0fc',...
    'foregroundcolor','black',...
    'String','f2=',...
    'Parent',Group6);

Be=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.33 0.65 0.23 0.05],...
    'foregroundcolor','black',...
    'String',num2str(f2),...
    'Callback','f2=str2num(get(gco,''String''))',...
    'Parent',Group6);

Pm=uicontrol("Style","popupmenu",...
    'Units','normalized',...
    'Position',[0.56 0.65 0.23 0.05],...
    'String','Hz|kHz',...
    'Value',Tipf2,...
    'Callback','Tipf2=get(gco,''Value'')',...
    'Parent',Group6);

Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.13 0.55 0.23 0.05],...
    'BackgroundColor','#95d0fc',...
    'foregroundcolor','black',...
    'String','Ph2=',...
    'Parent',Group6);

Be=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.33 0.55 0.23 0.05],...
    'foregroundcolor','black',...
    'String',num2str(Ph2),...
    'Callback','Ph2=str2num(get(gco,''String''))',...
    'Parent',Group6);


Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.03 0.45 0.10 0.05],...
    'BackgroundColor','#95d0fc',...
    'foregroundcolor','black',...
    'String','V3:',...
    'Parent',Group6);

Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.13 0.45 0.2 0.05],...
    'BackgroundColor','#95d0fc',...
    'foregroundcolor','black',...
    'String','Ampl3=',...
    'Parent',Group6);

Be=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.33 0.45 0.23 0.05],...
    'foregroundcolor','black',...
    'String',num2str(Ampl3),...
    'Callback','Ampl3=str2num(get(gco,''String''))',...
    'Parent',Group6);

Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.13 0.35 0.2 0.05],...
    'BackgroundColor','#95d0fc',...
    'foregroundcolor','black',...
    'String','A3=',...
    'Parent',Group6);

Be=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.33 0.35 0.23 0.05],...
    'foregroundcolor','black',...
    'String',num2str(A3),...
    'Callback','A3=str2num(get(gco,''String''))',...
    'Parent',Group6);

Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.13 0.25 0.23 0.05],...
    'BackgroundColor','#95d0fc',...
    'foregroundcolor','black',...
    'String','f3=',...
    'Parent',Group6);

Be=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.33 0.25 0.23 0.05],...
    'foregroundcolor','black',...
    'String',num2str(f3),...
    'Callback','f3=str2num(get(gco,''String''))',...
    'Parent',Group6);

Pm=uicontrol("Style","popupmenu",...
    'Units','normalized',...
    'Position',[0.56 0.25 0.23 0.05],...
    'String','Hz|kHz',...
    'Value',Tipf3,...
    'Callback','Tipf3=get(gco,''Value'')',...
    'Parent',Group6);

Bt=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.13 0.15 0.23 0.05],...
    'BackgroundColor','#95d0fc',...
    'foregroundcolor','black',...
    'String','Ph3=',...
    'Parent',Group6);

Be=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.33 0.15 0.23 0.05],...
    'foregroundcolor','black',...
    'String',num2str(Ph3),...
    'Callback','Ph3=str2num(get(gco,''String''))',...
    'Parent',Group6);

Pm=uicontrol("Style","popupmenu",...
    'Units','normalized',...
    'Position',[0.2 0.05 0.45 0.05],...
    'String','Sinusoidal|Dreptunghiular|Triunghiular|Dinte de fierastrau',...
    'Value',TipSemnal,...
    'Callback','TipSemnal=get(gco,''Value'')',...
    'Parent',Group6);

m=uimenu('Label','Documentație');
uimenu(m,'Label','Titlu proiect','Callback','open("Titlu_proiect.htm")');
uimenu(m,'Label','Descriere proiect','Callback','open("Descriere proiect.htm")','Separator','on');
uimenu(m,'Label','Relații matematice','Callback','open("Relatii matematice.htm")');
uimenu(m,'Label','Capturi de ecran','Callback','open("Capturi de ecran din proiect.htm")');
uimenu(m,'Label','Bibliografie','Callback','open("Bibliografie.htm")','Separator','on');

